### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by zhang-xiang** [artdong/vue-admin#7]
vue-cli 是2.X.X具体哪个版本的，Failed at the vue-admin@1.0.5 dev script.这个错误是否和版本有关系

**Comment by artdong** [comment]
> vue-cli 是2.X.X具体哪个版本的，Failed at the vue-admin@1.0.5 dev script.这个错误是否和版本有关系

检测你的8080端口是否被占用  @zhang-xiang
